version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Instalando dependencias de Maven si no están en caché..."

  pre_build:
    commands:
      - echo "Iniciando pre-build..."
      - mvn clean

  build:
    commands:
      - echo "Ejecutando tests..."
      - mvn test
      - echo "Construyendo JAR..."
      - mvn package -DskipTests=false
      
      # Crear carpeta de distribución
      - mkdir -p build-output
      # Copiar el JAR
      - cp target/*.jar build-output/

      # Crear ZIP que Beanstalk necesita
      - cd build-output
      - zip ../artifact.zip *.jar
      - cd ..

  post_build:
    commands:
      - echo "Build completado exitosamente."

artifacts:
  files:
    - artifact.zip
  discard-paths: yes