version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Instalando Maven..."
      - mvn --version

  pre_build:
    commands:
      - echo "Limpiando proyecto..."
      - mvn clean

  build:
    commands:
      - echo "Ejecutando tests..."
      - mvn test
      - echo "Construyendo JAR..."
      - mvn package -DskipTests=false
      - echo "Preparando artifact para Elastic Beanstalk..."
      - cp target/*.jar app.jar
      - echo "web: java -jar app.jar" > Procfile
      - zip artifact.zip app.jar Procfile

artifacts:
  files:
    - artifact.zip
  discard-paths: yes