version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Instalando dependencias de Maven..."
      # Maven ya viene instalado en la imagen de CodeBuild Java
      - mvn --version

  pre_build:
    commands:
      - echo "Limpiando build anterior..."
      - mvn clean

  build:
    commands:
      - echo "Compilando proyecto y ejecutando tests..."
      - mvn package -DskipTests=false

      - echo "Preparando ZIP para Elastic Beanstalk..."
      # Crear carpeta temporal para artifact
      - mkdir -p eb-artifact
      # Copiar el JAR a la carpeta temporal
      - cp target/*.jar eb-artifact/
      # Crear ZIP directamente con el JAR en la raíz
      - cd eb-artifact
      - zip -r ../artifact.zip *
      - cd ..
      - echo "ZIP creado correctamente: artifact.zip"

  post_build:
    commands:
      - echo "Build completado exitosamente."

artifacts:
  files:
    - artifact.zip
  discard-paths: yes
