version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - mvn --version

  pre_build:
    commands:
      - mvn clean

  build:
    commands:
      - mvn test
      - mvn package -DskipTests=false
      - cp target/*.jar app.jar
      - echo "web: java -jar app.jar" > Procfile
      - zip artifact.zip app.jar Procfile

  post_build:
    commands:
      - true

artifacts:
  files:
    - artifact.zip
  discard-paths: yes
