version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Instalando dependencias de Maven si no están en caché..."

  pre_build:
    commands:
      - echo "Iniciando pre-build..."
      - mvn clean

  build:
    commands:
      - echo "Ejecutando tests..."
      - mvn test
      - echo "Construyendo JAR..."
      - mvn package -DskipTests=false

      - echo "Creando carpeta de distribución..."
      - mkdir -p build-output
      - cp target/*.jar build-output/

      - echo "Creando artifact.zip para Elastic Beanstalk..."
      - cd build-output
      - zip -r ../artifact.zip *
      - cd ..

  post_build:
    commands:
      - echo "Build completado exitosamente. artifact.zip listo para Beanstalk."

artifacts:
  files:
    - artifact.zip
  discard-paths: yes
