version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Instalando dependencias de Maven si no están en caché..."

  pre_build:
    commands:
      - echo "Iniciando pre-build..."
      - mvn clean
      - mvn validate

  build:
    commands:
      - echo "Ejecutando tests y construyendo JAR..."
      - mvn package

      # Crear ZIP listo para Elastic Beanstalk
      - echo "Empaquetando JAR en artifact.zip..."
      - zip -j artifact.zip target/*.jar

  post_build:
    commands:
      - echo "Build completado exitosamente."

artifacts:
  files:
    - artifact.zip
  discard-paths: yes
