version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Instalando Maven..."
      - mvn --version

  pre_build:
    commands:
      - echo "Limpiando proyecto..."
      - mvn clean

  build:
    commands:
      - echo "Ejecutando tests..."
      - mvn test
      - echo "Construyendo JAR..."
      - mvn package -DskipTests=false
      - echo "Preparando artifact para Elastic Beanstalk..."
      - mkdir -p build-output
      - cp target/*.jar build-output/app.jar
      - echo "web: java -jar app.jar" > build-output/Procfile
      - cd build-output
      - zip -r ../artifact.zip *
      - cd ..

  post_build:
    commands:
      - echo "Build completado correctamente."

artifacts:
  files:
    - artifact.zip
  discard-paths: yes
