version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Instalando dependencias Maven..."
      - mvn --version

  pre_build:
    commands:
      - echo "Limpiando proyecto..."
      - mvn clean

  build:
    commands:
      - echo "Ejecutando tests..."
      - mvn test
      - echo "Construyendo JAR..."
      - mvn package -DskipTests=false

      # Crear carpeta temporal deploy
      - mkdir -p deploy
      # Copiar JAR y renombrar
      - cp target/*.jar deploy/app.jar
      # Crear Procfile opcional
      - echo "web: java -jar app.jar" > deploy/Procfile
      # Crear ZIP listo para Beanstalk
      - cd deploy
      - zip -r ../artifact.zip *
      - cd ..

  post_build:
    commands:
      - echo "Build completado exitosamente. Artifact listo para Elastic Beanstalk."

artifacts:
  files:
    - artifact.zip
  discard-paths: yes
