name: Puppet Manual Run

on:
  workflow_dispatch:

jobs:
  puppet-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repo
        uses: actions/checkout@v4

      - name: Actualizar paquetes
        run: sudo apt-get update

      - name: Instalar Puppet
        run: sudo apt-get install -y puppet

      - name: Validar sintaxis del manifest
        run: puppet parser validate manifests/site.pp

      - name: Aplicar manifest (modo simulación)
        run: sudo puppet apply manifests/site.pp
      
      - name: Verificar que nginx esté instalado
        run: dpkg -l | grep nginx
